[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=3.4.3"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "plumbum/version.py"
write_to_template = "__version__ = version_string = \"{version}\"\nversion = tuple(int(n) for n in version_string.split(\".\")[:3])\n"
